[package]
name = "storage"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
bincode = "1.3.3"
thiserror = "2.0.3"
my_core = { package = "core", path = "../core" }
serde = "1.0.215"
tokio = { version = "1.41.1", features = ["full"] }
