[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
as-any = "0.3.1"
async-trait = "0.1.83"
bincode = "1.3.3"
dyn-clone = "1.0.17"
serde = { version = "1.0.215", features = ["serde_derive"] }
serde_yaml = "0.9.34"
thiserror = "2.0.3"
